version: "2"

services:
  # https://docs.docker.com/docker-hub/builds/automated-testing/
  sut:
    build:
      context: ./test
      dockerfile: Dockerfile
    depends_on:
      - guacd
      - guacamole
      - db
    volumes_from:
      - guacd
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  guacd:
    # For development or CI, tag build from local Dockerfile
    build:
      context: ./
      dockerfile: Dockerfile
      args: 
        - TAG=${TAG}
        - VCS_REF=${VCS_REF}
        - BUILD_DATE=${BUILD_DATE}
    # For production, download prebuilt image
    #image: ${IMAGE_NAME}
    container_name: guacd
    restart: always
    environment:
      # Log Config
      - GUACD_LOG_LEVEL=info
    volumes:
      - /srv/guacamole/shared:/srv/guacamole/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  guacamole:
    image: guacamole/guacamole:%%VERSION%%
    container_name: guacamole
    hostname: guacamole
    restart: always
    ports:
      - "80:8080"
    links:
      - guacd:guacd
    depends_on:
      - guacd
      - postgres
    environment:
      # Guacd Config
      - GUACD_HOSTNAME=guacd
      - GUACD_PORT=4822
      # Guacamole Config
      - GUACAMOLE_HOME=/srv/guacamole/
      # Postgres Config
      - POSTGRES_HOSTNAME=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=${GUACAMOLE_DB_NAME}
      - POSTGRES_USER=${GUACAMOLE_DB_USER}
      - POSTGRES_PASSWORD=${GUACAMOLE_DB_PWD}
    volumes:
      - /srv/guacamole/app:/srv/guacamole/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  postgres:
    image: postgres:11-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=${GUACAMOLE_DB_NAME}
      - POSTGRES_USER=${GUACAMOLE_DB_USER}
      - POSTGRES_PASSWORD=${GUACAMOLE_DB_PWD}
    volumes:
      - /srv/guacamole/db/data/:/var/lib/postgresql/data
      - /srv/guacamole/config/:/srv/guacamole/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
